### ISSUE TITLE
Proxy handler should be able to retry its upstream request with different server

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#168]
Consider the situation where there is a `upstream` with more than one server which should be synchronized. Synchronized in the sense that the two storage servers should have the same files between them. In nedomi config this would mean:

```
"upstreams": {
  "synchronized": {
    "servers": [
      "first.example.com",
      "second.example.com"
    ]
  }
}
```

Now, the synchronization between the two upstream servers may be slow (a minute, an hour?) for some reason. When a file is uploaded on one of them, it takes time to be replicated to the other. During this time nedomi will report 404 or 200 for the same file path depending on which upstream server was selected. We must have a mechanism to tell nedomi (or rather, its proxy handler) to retry with the next upstream on some kind of HTTP codes.

This situation is further complicated by the fact we are keeping parts of files and not the whole file itself. So it is a possibility for a request to be partly satisfied by a locally stored parts and partly from an upstream configured in the above manner.

My proposal is a new `proxy` handler setting key which will trigger the above behaviour. Maybe

```
"retry_upstream_on": [401, 402, 404]
```

With this switch the current (more efficient) behaviour will be preserved by default.

**Comment by ironsmile** [comment]
After some thinking on the subject I came to the conclusion it might be a better idea if this `retry_upstream_on` option is an upstream setting. This way the whole retrying can be hidden from the proxy module which is complex enough by itself.

Along with that an additional setting will be needed - a way for setting a limit of the retries. Maybe `max_retries`.

**Comment by MStoykov** [comment]
Upstreams as such are only supposed to tell you which address to use. They have nothing to do with the actual request. 

I propose adding this as a feature to the proxy handler with the following settings proposition: 

```json
{
    "type": "proxy",
    "try_other_upstream_on_code": {
         "404": "name_of_upstream_404",
         "500": "name_of_upstream_500"
    }
}
```
which will mean : 
* if a request gets a code 404 it will be retried against the "name_of_upstream_404" upstream and it's returned
* Respectfully the same goes for request which gets 500 and upstream "name_of_upstream_500"
* In both cases the retried request is final and is what is returned even if the code is the same, different, or one that would've been retried if it wasn't a retry already.  So if at a request first gets 404 and then when retried it's returned no matter what the status code is(500 for example)


p.s. the keys have to be string because the keys of [json object](http://www.json.org/) are string

**Comment by ironsmile** [comment]
:+1:

**Comment by MStoykov** [comment]
is this fixed ?

**Comment by ironsmile** [comment]
I was hoping the mention in the commit will close the issue.
