### ISSUE TITLE
fmtPolice

### ISSUE THREAD

**Issue by MStoykov** [ironsmile/nedomi#22]
Are we gonna enable it and will we follow everything 'go vet' and 'go lint' suggests about the code?

**Comment by ironsmile** [comment]
I say we must make sure `go vet` does not show any errors. The linter is another matter. I don't think I'll have the self control to satisfy its requirements. But I can try!

**Comment by MStoykov** [comment]
f68f474304b6395af2d6d22248185fd2db910f8e does away with `go vet` warnings.

Although I have to mention that apparently I misguided you `fmtPolice` runs only `gofmt` (and shows diffs if any) and `go lint`. 

Maybe I should extent it to do `gofmt` and `go vet` and make it fail the build? or do maybe we don't want this to fail the build.

**Comment by ironsmile** [comment]
Well, ok you are right. This is my take:

`gofmt` *must* fail the build.

`go vet` should be run on every build so that we can have the information somewhere. But it may be better idea if it did not stop the build.

The linter *must not* be included in the build. We might keep it for information or not. Personally I don't have any feelings either way.
